version: 0.2

phases:
  install:
    commands:
      - cat /etc/os-release
      - echo Installing NGINX
      - sudo yum clean all
      - sudo yum update -y
      - sudo yum install nginx -y
      - nginx -v
  build:
    commands:
      - echo Building started on `date`
      - ls -lh /usr/share/nginx/html
      - sudo cp index.html /usr/share/nginx/html/
  post_build:
    commands:
      - echo Configuring NGINX
      - sudo systemctl enable nginx
      - sudo systemctl start nginx

artifacts:
  files:
    - '**/*'
  discard-paths: yes
