version: 0.2

phases:
  install:
    commands:
      - cat /etc/os-release
      - echo Installing NGINX
      - rm -rf /var/cache/yum
      - sudo rpm --erase gpg-pubkey-7fac5991-* || true
      - wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo rpm --import -
      - sudo yum clean all
      - sudo yum update -y
      - sudo yum install nginx -y
      - nginx -v
  build:
    commands:
      - echo Building started on `date`
      - ls -lh /usr/share/nginx/html
      - sudo cp index.html /usr/share/nginx/html/
  post_build:
    commands:
      - echo Configuring NGINX
      - sudo systemctl enable nginx
      - sudo systemctl start nginx

artifacts:
  files:
    - '**/*'
  discard-paths: yes
