version: 0.2

phases:
  install:
    commands:
      - cat /etc/os-release
      - echo Installing NGINX
      - sudo apt-get update -y
      - sudo apt-get install nginx -y
  build:
    commands:
      - echo Building started on 'date'
      - cp index.html /var/www/html/
  post_build:
    commands:
      - echo Configuring NGINX

artifacts:
  files:
    - '**/*'
  discard-paths: yes
