version: 0.2

phases:
  install:
    commands:
      - cat /etc/os-release
      - echo Installing NGINX
      - sudo apt clean all
      - sudo apt update -y
      - sudo apt install nginx -y
      - nginx -v
  build:
    commands:
      - echo Building started on 'date'
      - ls -lh /var
      - sudo cp index.html /var/www/html/
  post_build:
    commands:
      - echo Configuring NGINX

artifacts:
  files:
    - '**/*'
  discard-paths: yes
