version: 0.2

phases:
  install:
    commands:
      - echo Installing necessary packages
      - sudo apt-get update -y
      - sudo apt-get install -y nginx
  pre_build:
    commands:
      - echo Configuring Nginx
      - sudo mkdir -p /var/www/html
      - sudo chmod -R 755 /var/www/html
      - if [ -d "./html" ]; then sudo cp -r ./html/* /var/www/html/; fi
  build:
    commands:
      - echo Starting Nginx server
      - sudo systemctl start nginx
      - echo Nginx server started successfully
  post_build:
    commands:
      - echo Build and server setup completed successfully
      - sudo systemctl status nginx
