version: 0.2

phases:
  install:
    commands:
      - hostname
      - echo Installing necessary packages
      - sudo apt-get update -y
      - sudo apt-get install -y nginx
  pre_build:
    commands:
      - echo Configuring Nginx
      - sudo mkdir -p /var/www/html
      - sudo chmod -R 755 /var/www/html
      - if [ -d "./html" ]; then sudo cp -r ./html/* /var/www/html/; fi
  build:
    commands:
      - echo Starting Nginx server
      - sudo nginx
      - echo Nginx server started successfully
  post_build:
    commands:
      - echo Validating Nginx configuration
      - sudo nginx -t
      - echo Build and server setup completed successfully
